name: port-packages
author: Gowtham Sai (gwthm.in@gmail.com)
description: Reports packages to getport
inputs:
  clientId:
    required: true
    description: 'Client ID'
  clientSecret:
    required: true
    description: 'Client secret'
outputs:
  port_packages:
    description: 'Port packages entity'
    value: ${{ steps.extract-packages.outputs.packages }}
runs:
  using: 'composite'
  steps:
    # Extract packages from package manager version file based on the language.
    - name: "Extract packages"
      id: extract-packages
      shell: bash
      run: |
        ruby ${{ github.action_path }}/packages.rb
        cat packages.txt >> "$GITHUB_OUTPUT"

    - name: "Report packages to port"
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ inputs.clientId }}
        clientSecret: ${{ inputs.clientSecret }}
        operation: BULK_UPSERT
        entities: ${{ steps.extract-packages.outputs.packages }}

