name: port-packages
author: Gowtham Sai (gwthm.in@gmail.com)
description: Reports port packages to getport
inputs:
  clientId:
    required: true
    description: 'Client ID'
  clientSecret:
    required: true
    description: 'Client secret'
runs:
  using: 'composite'
  steps:
    # Extract packages from package manager version file based on the language.
    - name: "Extract packages"
      id: extract-packages
      shell: bash
      run: |
        ruby ${{ github.action_path }}/packages.rb
        cat packages.txt >> "$GITHUB_OUTPUT"
        echo "Packages...."
        cat packages.txt

    - name: "Extract packages identifiers"
      id: extract-packages-identifiers
      shell: bash
      run: |
        echo "identifiers=$(echo '${{steps.extract-packages.outputs.packages}}' | jq --compact-output -r '[.[] | .identifier]')" >> "$GITHUB_OUTPUT"

    - name: "Report packages to port"
      uses: port-labs/port-github-action@v1
      with:
        clientId: ${{ inputs.clientId }}
        clientSecret: ${{ inputs.clientSecret }}
        operation: BULK_UPSERT
        entities: ${{ steps.extract-packages.outputs.packages }}

